x-doppler: &doppler-env
  environment:{{range $key, $value := .}}
    - {{$key}}{{end}}

services:
  torrent-watcher:
    build: .
    container_name: torrent-watcher
    <<: *doppler-env
    volumes:
      - ./data:/usr/data
      - ./logs:/usr/logs
    restart: unless-stopped
