name: Deploy

on:
  pull_request:
    types:
      - closed
    branches:
      - release

jobs:
  deploy:
    name: Test Job
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: "Post deploy request"
        run: curl ${{ secrets.DEPLOYER_HOST }} -X POST --data '{"project":"${{ github.event.repository.name }}"}'
