name: Deploy

on: push

jobs:
  test-deploy:
    name: Test Job
    runs-on: ubuntu-latest
    steps:
      - name: "Post deploy request"
        run: echo ${{ github.event.repository.name }}
        # run: curl ${{ secrets.DEPLOYER_HOST }} -x POST --data '{"project":"${{ github.event.repository.name }}"}'
