name: Deploy

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  tests:
    name: Tests
    uses: ./.github/workflows/pr.yml

  deploy:
    if: ${{github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'deploy')}}
    name: Deploy
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: "Deploy request"
        run: curl --fail-with-body --silent ${{ secrets.DEPLOYER_HOST }} -X POST --data '{"project":"${{ github.event.repository.name }}"}'
