name: Deploy

on:
  push:
    branches:
      - main

jobs:
  tests:
    name: Tests
    uses: ./.github/workflows/tests.yml

  deploy:
    name: Deploy
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: "Post deploy request"
        run: curl --fail-with-body --silent ${{ secrets.DEPLOYER_HOST }} -X POST --data '{"project":"${{ github.event.repository.name }}"}'
