name: Deploy

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    needs: tests
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'deploy') }}
    steps:
      - name: DEBUG - merged status
        run: echo ${{ github.event.pull_request.merged }}
      - name: DEBUG - condition status
        run: echo ${{ github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'deploy') }}
      - name: "Deploy request"
        if: false
        run: curl --fail-with-body ${{ secrets.DEPLOYER_HOST }} -X POST --data '{"project":"${{ github.event.repository.name }}"}'

  tests:
    name: Tests
    uses: ./.github/workflows/tests.yml
