name: Testing and Linting

on:
  pull_request:
  workflow_call:

jobs:
  add-label:
    name: Add Label
    permissions: write-all
    if: ${{github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'main'}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            py:
              - '**.py'
      - uses: christianvuerings/add-labels@v1
        if: steps.filter.outputs.py == 'true'
        with:
          labels: deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test:
    name: Tests
    runs-on: ubuntu-latest
    env:
      MEDIA_DOWNLOAD_PATH: "/media"
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install Dev Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: Run tests
        run: pytest

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install Dev Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: Run lint
        run: flake8
