name: PR

on:
  pull_request:

jobs:
  add-label:
    name: Add Label
    if: ${{ github.event_name == 'pull_request' && github.event.action != 'closed' && github.event.pull_request.base.ref == 'main' }}
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            py:
              - '**.py'
      - uses: christianvuerings/add-labels@v1
        if: steps.filter.outputs.py == 'true'
        with:
          labels: deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  tests:
    name: Tests
    uses: ./.github/workflows/tests.yml

  debug-deploy:
    name: Debug Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Output pull request merged
        run: echo ${{github.event.pull_request.merged}}
      - name: Output pull request lables contains deploy
        if: false
        run: echo ${{contains(github.event.pull_request.labels.*.name, 'deploy')}}
      - name: Output whole condition
        if: ${{ github.event.pull_request.merged == false && contains(github.event.pull_request.labels.*.name, 'deploy') }}
        run: echo ${{ github.event.pull_request.merged == false && contains(github.event.pull_request.labels.*.name, 'deploy') }}
