name: Setup Python

on:
  workflow_call:

jobs:
  setup-job:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11.1"
          cache: "pipenv"
      - name: Install Pipenv
        run: pip install pipenv
      - name: Install Dependecies
        run: pipenv sync -d
