name: Test workflow

on:
  pull_request:
    branches:
      - main

jobs:
  tests:
    name: Tests
    uses: ./.github/workflows/tests.yml

  blank_job:
    name: Blank job
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: "Post deploy request"
        run: echo "ran!"
