name: Test workflow

on: pull_request

jobs:
  test_job:
    if: ${{github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'deploy')}}
    name: Test job
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hi!"
